version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/backup_postgre.sql:/docker-entrypoint-initdb.d/backup_postgre.sql

  bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - .:/bot
      - sqlite_data:/bot/app

volumes:
  pg_data:
  sqlite_data:
